#!/usr/bin/env bash
# This script 
sudo apt update
sudo apt install -y certbot python3-certbot-nginx
sudo ss -tlnp | grep ':80'
sudo service haproxy stop
sudo certbot certonly --standalone -d www.lanico.tech --non-interactive --agree-tos --email lawani.gk@gmail.com
sudo mkdir -p /etc/haproxy/certs
DOMAIN='www.lanico.tech' sudo -E bash -c 'cat /etc/letsencrypt/live/$DOMAIN/fullchain.pem /etc/letsencrypt/live/$DOMAIN/privkey.pem > /etc/haproxy/certs/$DOMAIN.pem'
sudo chmod -R go-rwx /etc/haproxy/certs
sudo cat /etc/haproxy/certs/www.lanico.tech.pem
sudo sed -i 'a#mode http#bind *:443 ssl crt /etc/haproxy/certs/www.lanico.tech.pem#'
