#!/usr/bin/env bash
# This script installs and configures an nginx web server
sudo apt-get update
sudo apt-get -y install nginx
sudo chown -R "$USER:$USER" /var/www
echo 'Hello World!' > /var/www/html/index.html
sudo service nginx restart
