#!/usr/bin/env bash
# This script 
user="replica_user"
host="%"
passwd="replica1"
sudo mysql -e "CREATE USER IF NOT EXISTS '$user'@'$host' IDENTIFIED WITH mysql_native_password BY '$passwd';"
sudo mysql -e "GRANT REPLICATION SLAVE ON *.* TO '$user'@'$host';"
sudo mysql -e "FLUSH PRIVILEGES;"
sudo mysql -e "GRANT SELECT ON mysql.user TO 'holberton_user'@'localhost';"
#I know this is insecure. I only did it since its a test environment.
mysql -uholberton_user -pprojectcorrection280hbtn -e 'SELECT user, Repl_slave_priv FROM mysql.user'
