#!/usr/bin/env bash
# This script installs fixes the Nginx configuration file to listen on port 80
sudo rm -rf /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default
sudo service nginx restart
