#!/usr/bin/env bash
#displays Best School 10 times, 
#but for the 9th iteration, 
#displays Best School and then Hi on a new line.
x=1
while [ $x -le 10 ]; do
    if (( x == 9 )); then
	    echo -e 'Best School\nHi'
    else
    echo "Best School";
	fi;(( x++ ))
done