#!/usr/bin/env bash
#displays Best School 10 times, 
#but for the 9th iteration, 
#displays Best School and then Hi on a new line.
x=1
while [ $x -le 9 ]; do
echo "Best School"; (( x++ ))
    if (( x == 9 )); then
	    echo 'Hi'
	fi; done