#!/usr/bin/env bash
#Displays ``Best School`` 10 times
x=1
while [ $x -le 10 ]; do
    if (( x == 4 )); then
	    echo 'bad luck'
	elif [ $x -eq 8 ]; then
        echo 'good luck'
    else echo "Best School";
	fi 
    (( x++ )); done